#!/usr/bin/env bash

# Check if argument is provided
if [ -z "$1" ]; then
  echo "Argument not provided."
else
  export VPC_ID="$1"
fi

if [ -z "$2" ]; then
  echo "Argument not provided."
else
  export IGW_ID="$2"
fi

if [ -z "$3" ]; then
  echo "Argument not provided."
else
  export SUBNET_ID="$3"
fi

if [ -z "$4" ]; then
  echo "Argument not provided."
else
  export ASSOCIATE_ID="$4"
fi

if [ -z "$5" ]; then
  echo "Argument not provided."
else
  export ROUTE_TABLE_ID="$5"
fi
## Detach IGW
aws ec2 detach-internet-gateway \
--internet-gateway-id $IGW_ID \
--vpc-id $VPC_ID

echo "Detached IGW: $IGW_ID"

## Delete IGW
aws ec2 delete-internet-gateway \
--internet-gateway-id $IGW_ID

echo "Deleted IGW: $IGW_ID"

## Disassociate subnet
aws ec2 disassociate-route-table \
--association-id $ASSOCIATE_ID

echo "Disassociated subnet."

## Delete Subnet
aws ec2 delete-subnet \
--subnet-id $SUBNET_ID

echo "Subnet deleted."

## Delete Route Table (The Route Table is removed already)
# aws ec2 delete-route-table --route-table-id $ROUTE_TABLE_ID

echo "Route table deleted."

## Delete VPC
aws ec2 delete-vpc --vpc-id $VPC_ID

echo "VPC deleted."