#!/usr/bin/env bash
echo "== create bucket"
# Check if at least one argument is provided
if [ -z "$1" ]; then
  echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
  exit 1
fi

BUCKET_NAME=$1
# https://docs.aws.amazon.com/cli/lastest/reference/s3api/create-bucket.html
aws s3api create-bucket \
 --bucket $BUCKET_NAME \
 --create-bucket-configuration="LocationConstraint=us-west-1" \
 --query Location \
 --output text